name: Build and Deploy
on:
  push:
    branches: ctb/dev-update
  schedule:
    - cron: "15 21 * * Mon,Fri"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CNAME_ml: term.clam.ml
      CNAME_moe: term.clam.moe
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
              yarn
              yarn build
              echo "${CNAME_ml}" | tee dist/CNAME
        env:
          PTTCHROME_THEME: 'clamtestbbs'
          PTTCHROME_PAGE_TITLE: "殼層體驗 Clam-Test BBS"
          DEFAULT_SITE: 'wsstelnet://ws.clam.ml/bbs'
          ALLOW_SITE_IN_QUERY: "no"
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          DEV_PROXY_TARGET: 'https://ws.clam.ml'
          DEV_PROXY_HEADER: 'https://term.clam.ml'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      - name: Install and Build
        run: |
              yarn
              yarn build
              echo "${CNAME_moe}" | tee dist/CNAME
        env:
          PTTCHROME_THEME: 'clamtestbbs'
          PTTCHROME_PAGE_TITLE: "Clam-Test BBS 殼層體驗"
          DEFAULT_SITE: 'wsstelnet://ws.clam.moe/bbs'
          ALLOW_SITE_IN_QUERY: "no"
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          DEV_PROXY_TARGET: 'https://ws.clam.moe'
          DEV_PROXY_HEADER: 'https://term.clam.moe'
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_TOKEN }}
        with:
          source-directory: 'dist'
          destination-github-username: 'clamtestbbs'
          destination-repository-name: ${{ env.CNAME_moe }}
          user-email: holishing@ccns.ncku.edu.tw
          target-branch: master
