name: Build and Deploy
on:
  push:
    branches: ctb/dev-update
  schedule:
    - cron: "15 21 * * Mon,Fri"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CNAME_moe: term.clam.moe
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install and Build
        run: |
              yarn
              yarn build
              echo "${CNAME_moe}" | tee dist/CNAME
        env:
          PTTCHROME_THEME: 'clamtestbbs'
          PTTCHROME_PAGE_TITLE: "Clam-Test BBS 殼層體驗"
          DEFAULT_SITE: 'wsstelnet://wsst.clam.moe/bbs'
          ALLOW_SITE_IN_QUERY: "no"
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          DEV_PROXY_TARGET: 'https://wsst.clam.moe'
          DEV_PROXY_HEADER: 'https://term.clam.moe'
          NODE_OPTIONS: '--openssl-legacy-provider'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: clamtestbbs/${{ env.CNAME_moe }}
          publish_branch: master
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'